In [ ]:
import torch

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.

In [ ]:
# list
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [ ]:
multidim = [[1,2,3],[2,3,4]]
multidim

[[1, 2, 3], [2, 3, 4]]

In [ ]:
# Numpy array
import numpy as np
np1 = np.random.rand(3,4)
np1

array([[0.76691392, 0.63890063, 0.8991509 , 0.93167021],
       [0.51412718, 0.29724038, 0.69551255, 0.78553534],
       [0.88415652, 0.74933718, 0.57793564, 0.06025543]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
# TENSORS
import torch
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.5000,  0.0820,  1.0477,  2.0685],
        [ 1.6211, -2.2999, -0.0695, -0.1319],
        [ 1.5341,  0.6810, -1.2026, -0.9945]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# tensor ops

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshape and view
mytorch = my_torch.reshape(2,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = my_torch2.reshape(5,-1)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch3.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5 = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch8 = my_torch.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [ ]:
# tensor math operations
# Add, Subtract, Multiply, Divide, Remainders, Exponents, shorthand and longhand, reassignment

import torch
import numpy as np


In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
#Addition

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
#subtraction

tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [ ]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
torch.div(tensor_b,tensor_a)


tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
torch.pow(tensor_b, tensor_a)

tensor([   5,   36,  343, 4096])

In [ ]:
#another way to write longhand

tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# reassignment
# tensor_a = tensor_a + tensor_b

tensor_a.add_(tensor_b)


tensor([ 6,  8, 10, 12])